name: thankyou_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.9+2
  flutter_email_sender: ^8.0.0
  flutter_settings_ui: ^3.0.1
  http: ^1.5.0
  image_cropper: ^9.1.0
  image_picker: ^1.2.0
  mailer: ^6.5.0
  path_provider: ^2.1.5
  sms_mms: ^0.0.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
